<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
  <OutputType>WinExe</OutputType>
  <TargetFramework>net9.0-windows</TargetFramework>
  <UseWindowsForms>true</UseWindowsForms>
  <Nullable>enable</Nullable>
  <ImplicitUsings>enable</ImplicitUsings>

  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  <SelfContained>true</SelfContained>

  <PublishSingleFile>true</PublishSingleFile>
  <PublishTrimmed>false</PublishTrimmed>

  <Optimize>true</Optimize>
  <DebugType>none</DebugType>

  <ApplicationIcon>Markadian Icon.ico</ApplicationIcon>
</PropertyGroup>



	<ItemGroup>
    <Content Include="LOGO_OFFICIAL_WHITE_SMALL - Copy.ico" />
    <Content Include="Markadian Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\Filip's Site Resources\LOGOS\Markadian Icon.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="7.1.1" />
    <PackageReference Include="LibVLCSharp.WinForms" Version="3.10.0" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="taglib-sharp-netstandard2.0" Version="2.1.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
    <PackageReference Include="Xabe.FFmpeg" Version="6.0.2" />
    <PackageReference Include="YoutubeExplode" Version="6.5.4" />
    <PackageReference Include="YoutubeExplode.Converter" Version="6.5.4" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>


</Project>